# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPrueba():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_prueba(self):
    # Test name: prueba
    # Step # | name | target | value
    # 1 | open | https://www.selenium.dev/documentation/webdriver/ | 
    self.driver.get("https://www.selenium.dev/documentation/webdriver/")
    # 2 | setWindowSize | 1050x832 | 
    self.driver.set_window_size(1050, 832)
    # 3 | click | css=.nav-item:nth-child(2) span | 
    self.driver.find_element(By.CSS_SELECTOR, ".nav-item:nth-child(2) span").click()
    # 4 | click | css=.nav-item:nth-child(3) span | 
    self.driver.find_element(By.CSS_SELECTOR, ".nav-item:nth-child(3) span").click()
    # 5 | click | css=.nav-item:nth-child(5) span | 
    self.driver.find_element(By.CSS_SELECTOR, ".nav-item:nth-child(5) span").click()
    # 6 | click | id=Layer_1 | 
    self.driver.find_element(By.ID, "Layer_1").click()
    # 7 | close |  | 
    self.driver.close()
  
